name: CI/CD pipeline

on:
  push:
  schedule:
    - cron: '0 0 * * 6'  # Run every Saturday at 9 AM JST

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pre-commit
        run: pip install pre-commit
      - run: pre-commit run --all-files

  deploy:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::691456347435:role/github-workflow-runner
          role-session-name: deploy
          # us-east-1 required since we're managing CloudFront resources
          aws-region: us-east-1
      - name: Derive stack name
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          echo "${DEFAULT_BRANCH}"
          STACK_NAME=beta
          if [ "${{ github.ref_name }}" == $DEFAULT_BRANCH ]; then
            STACK_NAME=prod
          fi
          echo "STACK_NAME=$STACK_NAME" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Install CDK
        run: npm install -g aws-cdk
      - run: cdk deploy "${STACK_NAME}"
